steps:

# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/argobot:latest', '.']
  env:
  - 'DOCKER_BUILDKIT=1'

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/argobot:latest'
  ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Waiting for SSH key propagation..."
      sleep 10
      gcloud compute ssh kharerishit@argobot-vm --zone=us-central1-a --tunnel-through-iap --command=" \
        docker-credential-gcr configure-docker --registries=us-central1-docker.pkg.dev && \
        docker pull us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/argobot:latest && \
        docker stop argobot || true && \
        docker rm argobot || true && \
        docker run -d \
          --name argobot \
          --env-file /home/kharerishit/.env \
          --restart unless-stopped \
          us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/argobot:latest"

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/argobot:latest'

options:
  logging: CLOUD_LOGGING_ONLY